#!/bin/sh

# pull latest
cd ..
git pull
cd docs

# copy the top level files
cp ../*.md . 
cp ../*.gif . 

# write an rst file for each
files="$(ls *.md|awk -F. '{print $1}')"
echo $files

for i in $files
do
  pandoc "$i.md" --from markdown --to rst -s -o "$i.rst"
  echo "$i.rst"
done

make html
# install the game
cp ../beau.html build/html


